openapi: "3.0.2"
info:
  title: DND Api
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      summary: Retrieve a list of users
      tags:
        - "Users"
      parameters:
        - name: page
          in: query
          description: The page number to retrieve
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: The number of users to retrieve per page
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          description: An error occurred while trying to list the users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new user
      tags:
        - "Users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
                - email
                - password
              properties:
                nickname:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: The new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: The requested username is already in use
        500:
          description: An error occurred while trying to create the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users/{id}:
    get:
      summary: Retrieve a single user
      tags:
        - "Users"
      parameters:
        - name: id
          required: true
          in: path
          description: The id of the user to retrieve
          schema:
            type: string
            pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
      responses:
        200:
          description: The requested user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid user id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: An error occurred while trying to retrieve the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update a single user
      tags:
        - "Users"
      parameters:
        - name: id
          required: true
          in: path
          description: The id of the user to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: The updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: The requested username is already in use
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: An error occurred while trying to update the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a user
      tags:
        - "Users"
      parameters:
        - name: userId
          in: query
          description: The id of the user to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: The user was successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: No user id specified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: An error occurred while trying to delete the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nickname:
          type: string
        email:
          type: string
          format: email
    Error:
      type: object
      properties:
        message:
          type: string
